Updated Twitter data processing to enable adding and changing topics.
mozilla-it/sumo pull request #16
Opened 2019-08-09 08:14 UTC by edin-ogtal

2019-08-12 06:06 UTC, ophie200 requested changes

2019-08-12 06:06 UTC, ophie200 commented on Product_Insights/Classification/upload_keywords_map.py
> +keywords_file = './Product_Insights/Classification/keywords_map.tsv'
where is this used?

2019-08-12 06:06 UTC, ophie200 commented on Product_Insights/Classification/upload_keywords_map.py
> +  job_config.skip_leading_rows = 1
Am getting Schema error: google.api_core.exceptions.BadRequest: 400 Provided Schema does not match Table imposing-union-227917:sumo.twitter_sentiment. Field in_reply_to_status_id_str has changed type from FLOAT to INTEGER
ugh, provide schema?

Please explicitly define schema.
  s = [
        bigquery.SchemaField("user_id", "INTEGER"),
        ...
        bigquery.SchemaField("id_str", "INTEGER"),
  ]
  job_config.autodetect = False
  job_config.schema = table_schema

2019-08-12 06:06 UTC, ophie200 commented on Product_Insights/Classification/upload_keywords_map.py
>  bucket_name = 'classification-test'
bq_client.dataset('sumo'), not 'analyse_and_tal'

2019-08-12 06:06 UTC, ophie200 commented on Product_Insights/Twitter/process_twitter_data.py
> +local_keywords_file = './Product_Insights/Classification/keywords_map.tsv'
please comment out- variable not used since passed as parameter via update_twitter_data.
in update_twitter_data, add default='./Product_Insights/Classification/keywords_map.tsv', to --keywordsmap
otherwise, local_keywords_file is None

Also, df = filter_language(df) may change df. Need to check df.empty for subsequent functions (run_sentiment_analysis, get_topics, save_results)

2019-08-14 09:23 UTC, edin-ogtal commented on Product_Insights/Classification/upload_keywords_map.py
> +keywords_file = './Product_Insights/Classification/keywords_map.tsv'
No where, will remove.

2019-08-14 09:29 UTC, edin-ogtal commented on Product_Insights/Classification/upload_keywords_map.py
>  bucket_name = 'classification-test'
fixed :)

2019-08-14 09:36 UTC, edin-ogtal commented on Product_Insights/Twitter/process_twitter_data.py
> +local_keywords_file = './Product_Insights/Classification/keywords_map.tsv'
added default and implemented checks.

2019-08-14 10:57 UTC, edin-ogtal commented on Product_Insights/Classification/upload_keywords_map.py
> +  job_config.skip_leading_rows = 1
Hmm, I can't reproduce this error on my end.
The twitter_sentiment table is explicitly defined in `Product_Insights/Twitter/create_twitter_tables.py` with the appropriate data types, so I'm not sure what is going on here. Also the changes made to `Product_Insights/Classification/upload_keywords_map.py` should not impact the twitter_sentiment table. 

Does this error occur when running: 
`python Product_Insights/Twitter/update_twitter_data.py --indataset sumo_views --intable twitter_mentions_view --outdataset sumo --outtable twitter_sentiment --bucket test-unique-bucket-name`
possible with the bucket parameter changed?

2019-08-16 23:19 UTC, merged